README.md
src/services/UrlGenerator.php

Added support for empty entry URIs

Hotfix entry uri

---

.craftplugin
CHANGELOG.md
src/services/fieldtranslator/Factory.php

- MultiOptionsFieldTranslator class to MultiSelectFieldTranslator

:bug: Updated MultiOptionsFieldTranslator class

---

.craftplugin
CHANGELOG.md
src/services/fieldtranslator/MultiSelectFieldTranslator.php
src/services/fieldtranslator/SingleOptionFieldTranslator.php
src/services/repository/TranslationRepository.php

Fixed issue with loading static translations for radio, multi-select, and dropdown field types.

:bug: Fixed issue with loading static translations for certain field types

---

.craftplugin
CHANGELOG.md
src/Translations.php

- Filter out console requests for _onDeleteElement() event

Resolve #134; Filter out console requests for _onDeleteElement() event

---

composer.lock

ACCL-42 :package: updated composer dependencies

---

src/services/fieldtranslator/MatrixFieldTranslator.php
src/services/fieldtranslator/NeoFieldTranslator.php
src/services/fieldtranslator/SuperTableFieldTranslator.php
src/services/repository/DraftRepository.php
src/services/translator/Export_ImportTranslationService.php

Added support for all field propagation method settings. This will need testing.

:construction: Support for propagation methods

---

src/templates/orders/_detail.twig

Updated text for Add Entries button

---

src/controllers/BaseController.php

Switch to using order total word count vs entry count for task processing

---

src/Translations.php
src/assetbundles/CategoryAssets.php
src/assetbundles/src/js/CategoryTranslations.js
src/controllers/BaseController.php
src/controllers/FilesController.php
src/migrations/Install.php
src/migrations/m200617_105526_create_category_draft_table.php
src/models/CategoryDraftModel.php
src/records/CategoryDraftRecord.php
src/services/App.php
src/services/UrlGenerator.php
src/services/repository/CategoryDraftRepository.php
src/services/repository/CategoryRepository.php
src/services/repository/DraftRepository.php
src/services/repository/FileRepository.php
src/services/translator/AcclaroTranslationService.php
src/services/translator/Export_ImportTranslationService.php
src/templates/categories/_editDraft.html
src/templates/orders/_detail.twig

ACCL-45 Added category support for translations

---

src/Translations.php

:card_file_box: :bookmark: Bumped schema version to 1.3.0

---

src/services/ElementToXmlConverter.php
src/services/ElementTranslator.php
src/services/fieldtranslator/AssetsFieldTranslator.php
src/services/fieldtranslator/Factory.php

- Support for custom asset fields

Asset field support

---

src/services/repository/DraftRepository.php
src/services/translator/AcclaroTranslationService.php
src/services/translator/Export_ImportTranslationService.php

- Better order log error messages for drafts that fail to save

Added char limit exceeded message for failed imports

---

src/assetbundles/src/js/OrderDetail.js
src/templates/orders/_detail.twig

- [URL Redirection to Untrusted Site ('Open Redirect')](https://cwe.mitre.org/data/definitions/601.html)
- [Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)](https://cwe.mitre.org/data/definitions/80.html)

Resolve reported medium security issues

---

src/Translations.php
src/assetbundles/src/css/Translations.css
src/services/job/ImportFiles.php
src/templates/orders/_detail.twig

- Manual file import for Acclaro API orders

Enable translated file import workflow for existing API orders

---

.craftplugin
CHANGELOG.md
src/services/repository/FileRepository.php

- `getFiles()` FileRecord query typo in `FileRepository.php`

Fixed typo in FileRecord query

---

src/services/api/AcclaroApiClient.php

PR sets 'craftcms' in Acclaro API create order calls within 'delivery' attribute

API- set 'CraftCMS' in delivery field for Acclaro API orders

---

.github/workflows/discord-notify.yml

- Added notifications for discord 🔉 🔔

Added workflow for notifications

---

src/assetbundles/src/js/OrderDetail.js

Fixed bug Adding Entries to a 'Saved' Order triggers new Order

---

src/Translations.php

- Fixed issue when applying drafts via Queue Manager by adding `run` to allowed draft actions

Fixed issue when applying drafts via Queue Manager

---

src/assetbundles/OrderAssets.php
src/assetbundles/src/js/CustomExporters.js
src/controllers/ExportController.php
src/services/Exporter.php
src/templates/orders/_index.twig

Added order export functionality

---

src/Translations.php
src/elements/Order.php
src/elements/db/OrderQuery.php
src/migrations/m210520_225356_add_order_due_date_column.php
src/services/translator/AcclaroTranslationService.php
src/templates/orders/_detail.twig

Due date sync and display feature

---

src/services/fieldtranslator/AssetsFieldTranslator.php

- Add Asset titles to XML files for translation (#170)
Targeted for the 1.10.5 release.

Asset title support

---

.github/workflows/discord-notify.yml

Updated discord notification action from `binotaliu/action-discord-notifier@v1` to `fateyan/action-discord-notifier@v1.2.0`

Updated discord notification action

---

src/services/repository/DraftRepository.php

Custom propagation method support

---

src/Translations.php
src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/AddEntriesToTranslationOrder.js
src/elements/Order.php
src/elements/db/OrderQuery.php
src/services/OrderSearchParams.php
src/services/repository/OrderRepository.php
src/templates/orders/_index.twig

Added source entry edit warning message

---

src/assetbundles/src/js/Dashboard.js
src/assetbundles/src/js/LanguageCoverage.js
src/assetbundles/src/js/RecentEntries.js
src/assetbundles/src/js/RecentlyModified.js
src/templates/_index.twig

- https://github.com/AcclaroInc/pm-craft-translations/issues/307

:bug: Fixed firefox dashboard and widget layout issues

---

src/models/CategoryDraftModel.php
src/models/GlobalSetDraftModel.php
src/services/repository/DraftRepository.php

Fixed bug - Order status not updating for Categories

---

src/services/fieldtranslator/AssetsFieldTranslator.php

Fixed bug - translated values not applied to assets

---

src/services/repository/DraftRepository.php

Fixed for matrix block merge issue

---

src/Translations.php

- Filter out console requests `_onBeforePublishDraft()` events https://github.com/AcclaroInc/pm-craft-translations/issues/326

Filter out console requests _onBeforePublishDraft event

---

src/controllers/BaseController.php
src/controllers/TranslatorController.php

- https://github.com/AcclaroInc/pm-craft-translations/issues/335

Fixed typo  #335

---

src/Translations.php
src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/ApplyTranslations.js
src/assetbundles/src/js/ExportFiles.js
src/assetbundles/src/js/ImportFiles.js
src/controllers/OrderController.php
src/controllers/WidgetController.php
src/elements/Order.php
src/services/App.php
src/services/UrlGenerator.php
src/services/job/ImportFiles.php
src/services/repository/DraftRepository.php
src/services/repository/ElementRepository.php
src/templates/categories/_editDraft.html
src/templates/orders/_detail.twig

- Minor feedback changes
- https://github.com/AcclaroInc/pm-craft-translations/issues/334
- https://github.com/AcclaroInc/pm-craft-translations/issues/345
- v2.0 issues with Globals
- Category drafts returning 404 error after file upload
- Category entry url is set to source instead of target after publishing draft
- Entry detail "Apply translations" action

Feedback changes from 9/15 review meeting

---

composer.json
composer.lock

Craft version updated to 3.7 to fix dependabot security alert

---

src/widgets/News.php

News Widget Guzzle client issue

---

README.md
src/templates/settings/settings-check.twig

- Minimum Craft version references

update: minimum required craft version

---

src/Constants.php
src/Translations.php
src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/OrderDetails.js
src/controllers/FilesController.php
src/controllers/OrderController.php
src/controllers/WidgetController.php
src/services/ElementToFileConverter.php
src/services/job/ImportFiles.php
src/services/repository/DraftRepository.php
src/services/repository/FileRepository.php
src/templates/orders/_detail.twig

- https://github.com/AcclaroInc/pm-craft-translations/issues/336#issuecomment-925385827

Order detail feedbacks

---

src/assetbundles/src/js/OrderDetails.js
src/controllers/OrderController.php
src/elements/Order.php
src/services/repository/DraftRepository.php
src/services/repository/FileRepository.php
src/services/translator/Export_ImportTranslationService.php
src/templates/orders/_detail.twig

Order feedback changes

---

src/assetbundles/src/js/OrderDetails.js
src/controllers/FilesController.php
src/controllers/OrderController.php
src/services/ElementToFileConverter.php
src/services/job/ImportFiles.php
src/services/repository/FileRepository.php

Changes to download the files from database

---

src/Translations.php
src/controllers/OrderController.php

Updated order status while applying draft from the detail page.

Updated status on apply draft from details page

---

src/assetbundles/src/js/OrderDetails.js
src/controllers/OrderController.php
src/services/repository/OrderRepository.php

1. Js disabling create order button in case or failed order.
2. Order Tags triggers update order button partially.
3. Order file title fix for non-entry type files.

Order Tags & disable create order button QA fixes

---

src/controllers/OrderController.php
src/migrations/Install.php
src/services/repository/TranslatorRepository.php

Updated install script to modify the database

---

src/services/repository/OrderRepository.php
src/templates/orders/_detail.twig

Added upload button, enable Sync button & fix API order issue

---

src/assetbundles/src/css/Translations.css
src/controllers/OrderController.php
src/elements/Order.php
src/services/repository/OrderRepository.php

Updates:
1. Added canceled filter on the order details page.
2. Author name fix.
3. API order fix with a due date.
4. Asset file formate issue fix.
5. CSS updates.

Added canceled filter, author name, asset file format error

---

src/services/job/ImportFiles.php

fix: Array to string conversion error when importing zip file

---

src/controllers/OrderController.php

fix: Order details template error

---

src/Constants.php
src/services/api/CraftApiClient.php
src/services/repository/SiteRepository.php

feat: Refactored lang alias logic and dynamically fetching the mapping

---

src/controllers/OrderController.php
src/services/repository/SiteRepository.php

fix: ISO mapping capitalization changes

---

src/controllers/BaseController.php
src/models/FileModel.php
src/services/UrlGenerator.php
src/services/job/RegeneratePreviewUrls.php
src/services/repository/DraftRepository.php
src/services/repository/FileRepository.php
src/templates/orders/_detail.twig

fix: Rebuild preview url header issue

---

src/services/UrlGenerator.php
src/services/repository/DraftRepository.php

fix: preview url issue while merge into draft

---

src/Constants.php
src/services/Exporter.php
src/services/api/CraftApiClient.php
src/services/repository/SiteRepository.php

Craft ISO dynamic mapping

---

src/controllers/OrderController.php
src/templates/orders/_detail.twig

feat: Add target site on the right side panel

---

src/assetbundles/src/js/OrderDetails.js

feat: Fix order detail review button position

---

src/services/Exporter.php

fix: Order export error

---

src/Constants.php
src/Translations.php
src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/ExportFiles.js
src/assetbundles/src/js/ImportFiles.js
src/assetbundles/src/js/OrderDetails.js
src/controllers/BaseController.php
src/controllers/FilesController.php
src/controllers/OrderController.php
src/controllers/SettingsController.php
src/elements/Order.php
src/migrations/Install.php
src/migrations/m211216_084350_add_pending_status_to_orders_table.php
src/models/FileModel.php
src/services/UrlGenerator.php
src/services/api/AcclaroApiClient.php
src/services/job/ImportFiles.php
src/services/repository/FileRepository.php
src/services/repository/OrderRepository.php
src/services/translator/AcclaroTranslationService.php
src/templates/orders/_detail.twig
src/templates/settings/configuration-options.twig

feat: added track changes

---

src/controllers/OrderController.php
src/services/api/AcclaroApiClient.php
src/services/repository/FileRepository.php
src/services/repository/OrderRepository.php
src/services/translator/AcclaroTranslationService.php

fix: Remove craft plugin plunet acclaro API info dependencies

---

src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/OrderDetails.js
src/templates/orders/_detail.twig

fix: Order details right sidebar fix & updated default status

---

composer.json
src/services/api/AcclaroApiClient.php
src/services/translator/AcclaroTranslationService.php

fix: added rate limiter for large order to send request on acclaro

---

src/controllers/SettingsController.php
src/models/Settings.php
src/services/api/AcclaroApiClient.php
src/templates/_layouts/settings.twig
src/templates/settings/configuration-options.twig

fix: added config option to record log and resolved logging issue

---

composer.json

fix: guzzle version update to 7

---

.craftplugin
CHANGELOG.md
composer.json

Release 2.1.1

---

src/controllers/FilesController.php
src/controllers/OrderController.php
src/services/repository/DraftRepository.php
src/services/translator/AcclaroTranslationService.php
src/services/translator/Export_ImportTranslationService.php

fix: Updates activity log status format

---

src/controllers/OrderController.php
src/elements/Order.php
src/services/repository/TagRepository.php
src/templates/_components/orders/settings-tab.twig

fix: tag labels missing after adding entry on create order

---

src/services/repository/SiteRepository.php

fix: ISO alias mapping issue

---

src/services/ElementTranslator.php

fix: exclude non-localized element titles

---

src/controllers/OrderController.php

fix: source site setting to default while adding new entry on create order

---

src/services/repository/FileRepository.php

fix: refactor generate preview url flow

---

src/controllers/FilesController.php
src/elements/Order.php
src/templates/orders/_detail.twig

feat: Allow file actions for Applied orders

---

src/assetbundles/src/css/Translations.css
src/assetbundles/src/js/OrderDetails.js
src/controllers/ExportController.php
src/templates/orders/_detail.twig

feat: download preview links

---

src/controllers/BaseController.php
src/elements/Order.php
src/services/repository/DraftRepository.php

fix:unchanged supertables target content on apply

---

src/controllers/BaseController.php
src/elements/Order.php
src/services/repository/DraftRepository.php

fix: Nested supertables fields fails to merge and apply

---

src/Translations.php
src/services/repository/DraftRepository.php
src/services/repository/OrderRepository.php

fix: Title missing apply draft error

---

src/Translations.php
src/services/repository/FileRepository.php

fix: plugin uninstall deleting entries

---

composer.json

Updated composer to required latest version with security fix.

---

composer.json

fix: craft min version updated

---

src/services/fieldtranslator/NeoFieldTranslator.php

fix: duplicate resname with neo fields

---

src/Constants.php
src/services/api/AcclaroApiClient.php

- Added order type `Website` to acclaro api `create_order()` call.

feat: added order type to acclaro api create order

---

src/services/job/ImportFiles.php

- Reverted from release/2.2.0 and made changes in this branch.

fix: issue applying non xml source contents

---

src/controllers/OrderController.php
src/services/fieldtranslator/VizyFieldTranslator.php
src/services/repository/DraftRepository.php
src/services/repository/FileRepository.php

- Fixed an issue where a vizy field is nested in another vizy field.
- Fixed issue with existing draft when source entry is updated and re merged.

fix: issue translating a vizy field inside other vizy field

---

src/services/repository/OrderRepository.php

- Api orders not syncing when order status new.

fix: Api order sync issue

---

src/services/fieldtranslator/VizyFieldTranslator.php

- Fixed an issue where translated content was not able to merge into draft because of non localised block

fix: vizy translations bug

---

src/services/fieldtranslator/VizyFieldTranslator.php

- fixed feedback issue where target not merged into draft.

fix: vizy translation issue

---

src/controllers/SettingsController.php
src/elements/actions/OrderDelete.php
src/services/fieldtranslator/MatrixFieldTranslator.php
src/services/fieldtranslator/NeoFieldTranslator.php
src/services/fieldtranslator/SuperTableFieldTranslator.php
src/templates/settings/clear-orders.twig

- Confirmation box on clear orders button in settings page.
- block id used similar as used in native nested blocks.
- Enhanced order deletion deletes drafts too when deleted from order index page.

Fix testing issues

---

src/services/fieldtranslator/MatrixFieldTranslator.php
src/services/fieldtranslator/NeoFieldTranslator.php
src/services/fieldtranslator/SuperTableFieldTranslator.php

fix:block id or new{index} uses while merging draft

---

src/controllers/FilesController.php
src/models/FileModel.php

fix: reference issue when entry not present in target site

---

src/services/repository/FileRepository.php

- Parsing error when comparing TM alignment content in order with an entry that contains special characters in target sites ([AcclaroInc/#483](https://github.com/AcclaroInc/pm-craft-translations/issues/483))

fix: error parsing special charecters

---

src/Constants.php
src/Translations.php
src/controllers/BaseController.php
src/controllers/FilesController.php
src/controllers/OrderController.php
src/controllers/SettingsController.php
src/controllers/WidgetController.php
src/models/Settings.php
src/services/App.php
src/services/ElementToFileConverter.php
src/services/Exporter.php
src/services/LogHelper.php
src/services/api/AcclaroApiClient.php
src/services/api/CraftApiClient.php
src/services/job/ImportFiles.php
src/services/repository/AssetDraftRepository.php
src/services/repository/CategoryDraftRepository.php
src/services/repository/CategoryRepository.php
src/services/repository/DraftRepository.php
src/services/repository/EntryRepository.php
src/services/repository/FileRepository.php
src/services/repository/GlobalSetDraftRepository.php
src/services/repository/GlobalSetRepository.php
src/services/repository/TagRepository.php
src/services/repository/TranslationRepository.php
src/services/repository/TranslatorRepository.php
src/services/translator/AcclaroTranslationService.php
src/templates/_components/orders/info-tab.twig
src/templates/settings/configuration-options.twig

Allow logging based on configuration settings

---

src/services/api/AcclaroApiClient.php

Merged branch master in release/3.0.0

Merge/master in release 3.0.0

---

src/templates/_components/_forms/order-files-table.twig

- Content missing from preview modal for first child

fix: missing preview content

---

src/widgets/News.php

- Updated logging for failure in getting acclaro feeds

update: log for graceful handling of acclaro feed failure

---

src/templates/settings/configuration-options.twig

Fix: save button toggle colour issue

---

src/controllers/BaseController.php
src/controllers/FilesController.php
src/controllers/OrderController.php
src/services/job/RegeneratePreviewUrls.php
src/services/job/SyncOrder.php
src/services/job/acclaro/SendOrder.php
src/services/job/acclaro/UpdateReviewFileUrls.php
src/services/translator/AcclaroTranslationService.php

Fixed: serialization error submitting order from queue

---

src/services/api/AcclaroApiClient.php

- An issue where target content was not synced in api order.

fixed: sync file action

---

src/assetbundles/src/js/OrderDetails.js
src/templates/_components/_forms/order-entries-table.twig

- `Add product` button on order detail page if commerce is installed.

added: add product button on order detail page if commerce is installed

---

src/services/translator/GoogleTranslationService.php

- An issue where google api was unable to handle translate request if request array size exceeds 128 indexes thus made chunks of 100 in such case

update: chunk down google translate array size if goes above 100

---

src/services/fieldtranslator/NeoFieldTranslator.php

- An issue where translated content failed to merge into draft.

fixed: error merging into draft

---

src/services/translator/AcclaroTranslationService.php

-  An issue where acclaro completed files failed to sync back onto craft.

Delivery files sync issue

---

src/controllers/SettingsController.php

- An issue where download log files was not working because of different date formats in different time zones.

fixed: log file download issue with different date formats

---

.craftplugin
CHANGELOG.md
src/elements/Order.php

- An issue where order listing page was taking too long to load.

Added: Fix for order detail page taking too long issue

---

src/services/ElementTranslator.php
src/services/repository/CommerceRepository.php

- An issue where merging changes to draft throwing error where commerce product/variant are referenced inside another commerce product/variant.

fixed: commerce draft merge issue

---

src/services/fieldtranslator/AssetsFieldTranslator.php

Made asset title only included in source when translatable.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: asset translation issue

---

src/services/fieldtranslator/AssetsFieldTranslator.php

- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Fixed: Asset title translation issue

---

.craftplugin
CHANGELOG.md
composer.json
src/services/repository/EntryRepository.php

Super table fields duplication issue when merged and applied fixed.
- #453 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
- An issue where super table fields were getting duplicated when merged and applied.
**Security:**
-
- 
**Checklist:**
[Include any additional notes, considerations, or context that may be …

Bug/543/super table fields duplicated on merge and apply (#454)

---

src/Translations.php

- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Fixed: issue element query executed before craft initialisation

---

.craftplugin
CHANGELOG.md
composer.json

Here we updated the min required craft version to `3.9.0` because of following two issues:
- The `Yiisoft/yii2` has released a fix for sql injection vulnerability in version >= `v2.0.47`.
- Craft cms vulnerable to Remote Code Execution via validatePath bypass fixed in `v3.8.15`. However the issue was fixed in `3.8.15` but we decided to go with `3.9.0` which also has the min `yiisoft/yii2` version required to `2.0.48`.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Screenshots (if …

updated: min craft version

---

.craftplugin
CHANGELOG.md
composer.json

Updated min craft version required to `4.4.15` to fix some vulnerabilities.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Updated: min required craft version

---

src/controllers/WidgetController.php

Users seeing error when loading plugin dashbaord provided craft get updates api is failing.
- [Update Craft 3 for Server Outage Issue](https://github.com/AcclaroInc/pm-craft-translations/issues/511)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

added: error handling for craft api call

---

src/Constants.php
src/services/fieldtranslator/Factory.php
src/services/fieldtranslator/HyperLinkFieldTranslator.php

- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Added: hyper link field support

---

.craftplugin
CHANGELOG.md
src/migrations/m240117_112821_create_activity_logs_table.php

Fixed an issue where migration failed for postgres database.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Fix failing migration if `activitylog` table is empty (#509)

---

src/services/fieldtranslator/AssetsFieldTranslator.php
src/services/fieldtranslator/HyperLinkFieldTranslator.php
src/services/fieldtranslator/MatrixFieldTranslator.php
src/services/fieldtranslator/NavigationFieldTranslator.php
src/services/fieldtranslator/NeoFieldTranslator.php
src/services/fieldtranslator/VizyFieldTranslator.php
src/services/repository/DraftRepository.php

Title missing error when creating/applying a darft having new fields.
- #518 
**Added:**
- Fallback for handles not found and logged for debugging.
**Changed:**
-
-
**Removed:**
- The title addition logic to new blocks as it does not have any title.
- Setting canonical values to draft prior to updating target content.
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: error applying new fields drafts

---

src/assetbundles/src/js/AddEntriesToTranslationOrder.js
src/assetbundles/src/js/AddTranslationsToCommerce.js
src/assetbundles/src/js/AssetsTranslations.js
src/assetbundles/src/js/CategoryTranslations.js
src/assetbundles/src/js/OrderDetails.js

Deselect target site individually if all are selected.
- [Target site selector not working](https://github.com/AcclaroInc/pm-craft-translations/issues/553)
- [New translation button not working](https://github.com/AcclaroInc/pm-craft-translations/issues/554)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: check box element selection issue

---

src/Constants.php
src/Translations.php
src/assetbundles/ServicesAssets.php
src/assetbundles/src/css/services.css
src/controllers/ServicesController.php
src/templates/services/_index.twig

Adding a dedicated page for services listing. 
Added a dedicated page for services pages
**Screenshots**
**Checklist:**
The links/buttons showing here need to be worked up - we would need to add those links for it to function properly.

#552: dedicated services page for marketing strategy

---

src/Constants.php
src/Translations.php
src/controllers/OrderController.php
src/services/job/SyncDataToHubSpotJob.php

Supports making a call to hubspot on installing or updating to craft 5 plugin
-  [ ] [#550](https://github.com/AcclaroInc/pm-craft-translations/issues/550)
**Added:**
Added a job to run on finishing of the installation
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
Steps:
1. Need to install n8n and setup the file shared for the execution to run in success.
[N8N configuration](https://drive.google.com/file/d/1vMKvpHaWk41yUKn4XPvHUkMAvkhCpug3/view?usp=sharing)
- 
**Checklist:**
@sidedwards We would need to setup n8n flow and at the same time would need the outh setup to be done there itself for this process to work. 
The rest of the work on email subscription and management would be resolved via HubSpot itself.

Hubspot integration support on install or update ( Marketing  strategy )

---

src/assetbundles/src/css/services.css

Fixed the css for services page
**Changed:**
Fixed the style alignment
**Checklist:**

fixed services page styling

---

src/migrations/Install.php

Added a fix for program id on orders
- 
**Fixed:**
Added the code for adding the program id to orders table
-
**Security:**
-
**Checklist:**

#532: fixed the install script for orders table

---

.craftplugin
CHANGELOG.md
src/elements/Order.php
src/models/FileModel.php
src/templates/_components/_forms/order-entries-table.twig
src/templates/_components/_forms/order-files-table.twig

Fixed UI some issues.
- [#565](https://github.com/AcclaroInc/pm-craft-translations/issues/565)
**Added:**
- 
**Changed:**
- The status class for new & pending statuses.
- The flex properties to fix title overflow in order settings & files tables.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: UI issues

---

.craftplugin
CHANGELOG.md
composer.lock
src/migrations/m241216_081944_upsert_program_id_column.php

- #541 
**Added:**
- A migration to add programId column if missing from table.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Release 4.0.4

---

src/controllers/BaseController.php

Header already sent error leading to server downtime.
- [Error: Headers already sent](https://github.com/AcclaroInc/pm-craft-translations/issues/573)
**Added:**
- 
**Changed:**
- echo statements with buffered output.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: headers already sent error

---

src/services/fieldtranslator/NeoFieldTranslator.php

Fixed Neo blocks content overwriting other sites content.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

fixed: neo block draft issue

---

.craftplugin
CHANGELOG.md
src/Constants.php
src/services/fieldtranslator/Factory.php
src/services/fieldtranslator/TableMakerFieldTranslator.php

Support for table maker plugin.
- [Support Table maker plugin](https://github.com/AcclaroInc/pm-craft-translations/issues/575)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Bp/575/table maker plugin support for craft5 (#551)

---

composer.json
composer.lock
src/assetbundles/src/css/Translations.css
src/templates/_components/orders/info-tab.twig

Craft . 5.6.* introduced some css changes in native css that impacted out order details sidebar has been fixed in this PR.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- Locally tested.
Before with craft 5.6
After fix:
**Checklist:**

fixed: css issue introduced in craft 5.6.*

---

src/assetbundles/src/js/OrderEntries.js

Removed an unwanted comma from in between an on event of javascript.
- #550 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

removed: unwanted comma

---

src/assetbundles/src/css/Translations.css

- #556 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

removed: custom css affecting craft UI

---

src/templates/_components/orders/info-tab.twig
src/templates/assets/_editDraft.twig

Deprecation warnings are see due to plugin code.
- #536 
**Added:**
- 
**Changed:**
- element hook with elementChip function.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**

Fixed: deprecation warning issues

---

src/services/fieldtranslator/CategoryFieldTranslator.php
src/services/repository/DraftRepository.php

Release 3.4.2
- [#593](https://github.com/AcclaroInc/pm-craft-translations/issues/593)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
- Category linked entries missing on draft creation.
**Security:**
-
- Testing criteria can be found on above linked ticker 593
**Checklist:**

fixed: category missing issue

---

src/controllers/FilesController.php
src/services/job/ImportFiles.php

Do not block file process like uploads, draft creation or apply when source content is modified.
- [Remove Source Modification Check](https://github.com/AcclaroInc/pm-craft-translations/issues/618)
**Added:**
- 
**Changed:**
-
-
**Removed:**
- Source modied check when uploading delivery files.
**Fixed:**
-
**Security:**
-
**Can be tested in dev instance**
- Create acclaro order.
- Download source files.
- Make changes in source entry content to trigger source modified alert.
- Once alert is visible try uploading the delivery (Translated) file.
- Ensure file is uploaded without any blockage followed by draft creation and applying should work without any issue.
- For more details …

removed: source change check

---

src/controllers/BaseController.php
src/controllers/FilesController.php
src/controllers/OrderController.php
src/elements/Order.php
src/elements/Translator.php
src/services/api/AcclaroApiClient.php
src/services/repository/OrderRepository.php

Saved the api order once the order is created and failed before submission.
- [Acclaro api call failure logging](https://github.com/AcclaroInc/pm-craft-translations/issues/588)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- Need to test all possible ways a user can submit order to acclaro.
**Checklist:**
___
Bug fix, Enhancement
___
- Add try/catch around API operations
- Convert silent failures to exceptions
- Improve error logging and user …

updated: handling of api call failures
