AcclaroInc/craft-translations

src/controllers/BaseController.php
- Redirect to new translation order vs thank-you page for failed API auth
=> ACCL-36 redirect for failed auth

src/Translations.php
Craft 3.4.6+ threw an error that explicitly required loading element\Order class in Translations.php
=> :bug: Added elements\Order class to Translations.php

src/services/job/ImportFiles.php
- Explicitly fail files if `resnameCheck()` fails
=> Failed file if resnames within the target file don't match

src/assetbundles/src/img/right-arrow.svg, src/assetbundles/src/js/OrderIndex.js, src/controllers/WidgetController.php, src/templates/_index.twig
=> New release notification on dashboard

src/services/UrlGenerator.php, src/services/repository/DraftRepository.php
- Deprecated `sourceId` method with `getCanonicalId()`
=> Updated deprecated sourceId method with getCanonicalId

src/services/translator/AcclaroTranslationService.php
- [`AcclaroTranslationService::getOrderUrl()`](https://github.com/AcclaroInc/craft-translations/blob/344203fa5648cc1daaf1315ff1ad5d2956bd3a18/src/services/translator/AcclaroTranslationService.php#L263-L268) method to use the new My Acclaro order pattern. https://github.com/AcclaroInc/pm-craft-translations/issues/317
=> Update getOrderUrl() to return the new My Acclaro order pattern

src/assetbundles/src/js/OrderDetails.js, src/controllers/OrderController.php, src/services/ElementToFileConverter.php, src/services/translator/AcclaroTranslationService.php
Following are the issues found in QA and fixed:
1. File download in json/csv format failing for asset elements.
2. Acclaro order's recent status not syncing on order detail page load.
3. Entries removed from source entries were added to the order after creating an order.
4. Draft title was not loading correctly.
5. Asset acclaro order issue with file format undefined variable.
=> New order testing issues fixes

src/elements/Order.php
=> fix: duplicate modified status on order index page

src/Constants.php
- Changed `iso_mapping` api endpoint to `acclarocraft.com`.
- Added new `grapgql` token for `iso_mapping_aliases` schema.
=> task: added new token and url for iso mapping

composer.json
- Updated min requirement for `guzzlehttp/guzzle` from 6.3 to 6.5.7
=> fix:guzzle version dependabot alert

src/controllers/OrderController.php, src/elements/actions/OrderDelete.php
=> fix: error when updating source content when no draft exists

src/Constants.php, src/models/FileModel.php, src/services/api/AcclaroApiClient.php
=> fix: missing api param in sycn order

src/Translations.php, src/controllers/OrderController.php, src/services/UrlGenerator.php, src/services/repository/TranslationRepository.php, src/templates/_components/orders/files-tab.twig
=> fix: translation rows removed on delete site

src/controllers/FilesController.php, src/controllers/OrderController.php, src/elements/Order.php, src/models/FileModel.php, src/services/ElementToFileConverter.php, src/services/job/ImportFiles.php, src/services/repository/DraftRepository.php, src/services/repository/FileRepository.php, src/services/translator/AcclaroTranslationService.php
1. Tm alert showed after source updated sync.
2. Applied files reverting to `In progress` when downloaded.
3. Upload translated files on `applied` order for `local` translator.
=> fix: showing tm alert after source update

src/models/FileModel.php, src/services/job/ImportFiles.php
- Tm alert being showed in order details page when importing updated translations on applied order ([AcclaroInc/#484](https://github.com/AcclaroInc/pm-craft-translations/issues/484))
=> fix: tm alert on importing translations

src/controllers/FilesController.php
- Error exporting source/reference file when target site for source entry does not exist. ([AcclaroInc/485](https://github.com/AcclaroInc/pm-craft-translations/issues/485))
=> fix: export source files if target doesent exists

src/Constants.php, src/migrations/Install.php, src/migrations/m220705_040234_change_preview_url_column_to_text.php, src/services/api/AcclaroApiClient.php, src/services/translator/AcclaroTranslationService.php
- An issue where order fails to open when preview url length exceeds 255 chars. ([AcclaroInc/#482](https://github.com/AcclaroInc/pm-craft-translations/issues/482)) 
- Removed the use of `filetype` param in api order sync call.
- Minimum required craft version.
=> fix: preview url column changed to text

src/services/fieldtranslator/AssetsFieldTranslator.php
- An issue where asset field type was missing from draft on merge ([AcclaroInc#489](https://github.com/AcclaroInc/pm-craft-translations/issues/489))
=> fix: asset mssing on merge into draft

src/services/fieldtranslator/GenericFieldTranslator.php
- An issue where redactor fields links missing their extra details in exported xml file. ([AcclaroInc#491](https://github.com/AcclaroInc/pm-craft-translations/issues/491))
This change however provides the missing data in exported xml file but links are still pointing to source site after translation.
Opened an issue in redactor repository for same [here](https://github.com/craftcms/redactor/issues/421)
=> updt: updated how generic translator proccess redactor fields

src/controllers/FilesController.php, src/services/fieldtranslator/MatrixFieldTranslator.php, src/services/fieldtranslator/NeoFieldTranslator.php, src/services/fieldtranslator/SuperTableFieldTranslator.php, src/services/translator/Export_ImportTranslationService.php
- Target missing from draft for orders that were created before update to v2.2.0 (xml resname keys are changed in this release)
- Tm files were getting synced for order that don't have track target changes enabled (i.e orders created before this feature was introduced)
=> Hotfix xml key mismatch old orders after update

src/controllers/OrderController.php, src/controllers/SettingsController.php, src/models/FileModel.php, src/models/Settings.php, src/services/Exporter.php, src/services/repository/DraftRepository.php, src/services/repository/FileRepository.php, src/services/repository/OrderRepository.php, src/services/repository/TranslatorRepository.php, src/templates/_components/orders/info-tab.twig, src/templates/settings/configuration-options.twig
- Removed changes for allowing a config setting to enable and disabled local translator.
- An error merging into draft where same draft id was conflicting for global set, category and assets drafts.
- An issue where global set title was not visible on file tab on order details page.
=> Fix: revert allow local order setting from config settings

src/assetbundles/src/js/OrderEntries.js, src/elements/Order.php, src/services/repository/OrderRepository.php, src/templates/orders/_detail.twig
- A bug where global config settings for track source/target changes was interfering with submitted orders track changes light switch.
- Download/Sync TM files option only available when user can see alert icon for target mismatch.
=> Fix category draft issue and refactor

src/widgets/News.php
If the newsfeed at acclaro.com is ever unavailable, fail gracefully and show an empty newsfeed.
=> fix: catch error when newsfeed is unreachable

src/elements/Order.php
=> Added: new quote statuses to sidebar filter

src/controllers/SettingsController.php, src/templates/settings/send-logs.twig
- Added date selector in send logs ([AcclaroInc#496](https://github.com/AcclaroInc/pm-craft-translations/issues/496))
=> Update: logic for send logs

src/Translations.php
- Plugin settings url throwing error ([AcclaoInc#497](https://github.com/AcclaroInc/pm-craft-translations/issues/497))
=> fixed: error opening plugin settings page

src/assetbundles/src/js/OrderDetails.js, src/controllers/OrderController.php
- An issue where clicking `save draft` button in detail page of an existing order draft was creating new draft.
=> fixed: creating new draft from existing for orders

src/templates/_components/app-info.twig, src/templates/_index.twig, src/templates/settings/about.twig
Plugin license was chowing as free trial even if user adds a paid license.
[#437] Paid version still shows `Free Trial`
**Added:**
- 
**Changed:**
- `craft.app.plugins.getPluginLicenseKeyStatus()` with `craft.app.plugins.getPluginInfo()` to check license status.
-
**Removed:**
- Unused code from `About` template.
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: plugin license status issue

.craftplugin, CHANGELOG.md, src/Translations.php, src/assetbundles/src/js/OrderDetails.js, src/controllers/BaseController.php, src/controllers/CommerceController.php, src/controllers/OrderController.php, src/controllers/WidgetController.php, src/templates/_index.twig
This PR includes a bug where log files were flooded by element query executed before craft is fully initialised along with some code refactors to reduce some extra actions in order controller.
- #456 
**Added:**
- A check before registering after plugin load events for if the craft is initialised.
**Changed:**
-
-
**Removed:**
- Clone order controller action that is to be done by using Save order action.
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
[Include any additional …
=> Release 3.2.9

src/templates/_index.twig
A twig error was shown when the dashboard is opened with craft running in dev mode and a new update of plugin is available.
- #461 
The update variable obtained as a response from craft update api used to be an object as the old code tries to check a key `releases` and now it's a boolean value so removed that check to prevent error.
**Added:**
- 
**Changed:**
-
-
**Removed:**
- The `updates.release` from logic as updates now is a boolean value. 
**Fixed:**
-
**Security:**
-
- Test to check we don't see an error page when an update is available and the dev mode is enabled for craft setup.
**Checklist:**
[Include any additional notes, …
=> fixed: error shown in dev mode when a new update is available

src/services/repository/DraftRepository.php, src/services/repository/EntryRepository.php
Drafts were not getting created for entries that are disabled for target site and showing success message to user.
- #463 
Ensured create draft does not show success when it fails and also fixed issue preventing draft creation for disabled target entry.
**Added:**
- A try catch block when creating draft to capture the exact issue and show error in case if any.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
- An issue where draft for a disabled entry in target site was not created.
**Security:**
-
- Test by creating an order and complete round trip for an entry which is disabled in target site.
**Checklist:**
[Include any additional notes, …
=> fixed: draft not created when entry is disabled in target site

src/services/repository/StaticTranslationsRepository.php
Fixed an error where static translation page was showing error after craft 4.5.0 upgrade.
- #468 
**Added:**
- 
**Changed:**
- A param to `Craft::t()` which actually needs to be an empty array in place of null.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: error opening static translation page after craft 4.5.0

src/controllers/FilesController.php
As we made a fix to error that arise after craft 4.5.0 update in which uploading delivery files was showing error, so we used crafts temp location for it due to which all asset uploads were sent to temp directory irrespective of what volume we select from plugins settings page. Now here we corrected the issue to use the volume if its not 0 and use temp location otherwise.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
[Include any relevant screenshots to …
=> fixed: an issue where uploaded assets saving to temp directory only

composer.json, composer.lock, src/services/api/GoogleApiClient.php, src/services/translator/GoogleTranslationService.php
Added google translate logic using google/cloud-translate library deprecating old guzzle client logic.
- #466 
**Added:**
- Google loud translation client for google translations.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> added: google translator library for google translations

src/services/repository/OrderRepository.php, src/services/translator/AcclaroTranslationService.php
The comment added to craft order on creation is not reflected on my acclaro's order comments tab.
- [Comments failing](https://github.com/AcclaroInc/pm-craft-translations/issues/516)
**Added:**
- Added a new function to process order comments to acclaro.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- Create a fresh order from craft cms to acclaro with some comment and see that comment on my acclaro order details page's comments section.
**Checklist:**
=> fixed: comments failing on acclaro issue

src/Constants.php, src/controllers/OrderController.php, src/controllers/SettingsController.php, src/elements/Order.php, src/migrations/Install.php, src/migrations/m240117_112821_create_activity_logs_table.php, src/models/ActivityLogModel.php, src/records/ActivityLogRecord.php, src/services/App.php, src/services/Exporter.php, src/services/repository/ActivityLogRepository.php, src/templates/orders/_detail.twig, src/templates/settings/send-logs.twig
Made some changes to store activity logs in a separate table to help in debugging.
- #521 Dedicated activity logs table
**Added:**
- New activity logs table
- Migration to create new activity logs table and move old activity logs from orders table to new logs table.
- A download activity logs button on send logs page in settings tab.
**Changed:**
- The logic to store and retrieve saved logs.
-
**Removed:**
- activity logs column from orders table.
**Fixed:**
-
**Security:**
-
- 
**Checklist:** …
=> Bp add new activity log table for logs

src/controllers/BaseController.php, src/models/GlobalSetDraftModel.php
Fixed file status reverting back to ready for review when its applied and we receive an order callback.
- #520
**Added:**
- A check before processing a file when receiving an order/file callback.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> added check for already merged file from reverting back via callback

src/Constants.php, src/services/fieldtranslator/Factory.php, src/services/fieldtranslator/GenericFieldTranslator.php
Add CKEditor field support.
- #490 
Handle CKEditor fields the same as Redactor fields.
**Checklist:**
=> Add CKEditor as a supported generic field type

src/migrations/Install.php, src/migrations/m240610_142319_update_translation_activitylogs.php
New plugin installs were having problem creating order due to bad column naming.
- #533/ on private repo
**Added:**
- A migration for existing installations.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
- The wrong column name from `targetclass` to `targetClass`.
**Security:**
-
- 
**Checklist:**
=> fixed: activity log table name issue

src/migrations/m240117_112821_create_activity_logs_table.php
```
*** applying m240117_112821_create_activity_logs_table
> create table {{%translations_activitylogs}} ... done (time: 0.121s)
> create index craft_idx_skbcykktosmeitobyjtmlufiryicduasxyck on {{%translations_activitylogs}} (targetId) ... done (time: 0.101s)
> create index craft_idx_vtzmdkqbtenjbxzizjuramanfhqmsmftejxu on {{%translations_activitylogs}} (targetClass) ... done (time: 0.050s)               Exception: foreach() argument must be of type array|object, null given (/app/vendor/acclaro/translations/src/migrations/m240117_112821_create_activity_logs_table.php:37)
```
=> Fix failing migration if `activitylog` table is empty

src/controllers/FilesController.php, src/controllers/OrderController.php, src/services/repository/DraftRepository.php
The order search is returning no results when searched for an order using name.
- [#542](https://github.com/AcclaroInc/pm-craft-translations/issues/542)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: order search bar issue

src/controllers/FilesController.php, src/controllers/OrderController.php, src/migrations/m240829_054957_drop_commerce_draft_table.php, src/services/repository/DraftRepository.php
Fixed the indexing issue causing no result when searching for an order from order listing page for old orders.
-
**Added:**
- Logic to re index existing orders within the remove commerce draft migration.
**Changed:**
- Removed index flag that prevent indexing when saving orders.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> added: existing order re-indexing to migration

.craftplugin, CHANGELOG.md, src/controllers/FilesController.php, src/controllers/OrderController.php, src/migrations/m240829_054957_drop_commerce_draft_table.php, src/services/fieldtranslator/AssetsFieldTranslator.php, src/services/fieldtranslator/HyperLinkFieldTranslator.php, src/services/fieldtranslator/MatrixFieldTranslator.php, src/services/fieldtranslator/NavigationFieldTranslator.php, src/services/fieldtranslator/NeoFieldTranslator.php, src/services/fieldtranslator/VizyFieldTranslator.php, src/services/repository/DraftRepository.php
Fixes for bugs found in beta1 release.
- 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> release v4.0.0-beta.2

src/controllers/TranslatorController.php
Added a extra check for program option if it is not set
Check for old translators already set up and programs should be enabled and disabled wisely.
**Checklist:**
=> #9415: edge case for old translators in program selections

src/services/ElementTranslator.php
Handled the case when same field is added multiple times in any nested field and the handle is changed by craft cms.
- [Multiple field handles for same field](https://github.com/AcclaroInc/pm-craft-translations/issues/555)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: duplicate field handle issue

src/assetbundles/src/js/RecentEntries.js, src/assetbundles/src/js/RecentlyModified.js
Fixes the null entry showing up on the dashboard when fetching new and modified source entries. 
- 
- When retrieving the list of entries, there are certain entries that have title as hidden, under these circumstances we get them as "Null" - now, the change here is to check for null and provide a default "Untitled" msg to make sure that the entry records exits and can be accessed. 
1. Create a new source entry or modify an existing one
2. Save the changes
3. Check the source entries display
4. Observe that instead of actual content, "Null" is shown for new entries
5. For modified entries, only slugs are visible instead of full content changes
**Checklist:**
=> fixed: handled source entry showing as null

.craftplugin, CHANGELOG.md, src/Translations.php, src/services/fieldtranslator/NeoFieldTranslator.php
Focuses on resolving block propagation issues related to nested fields neo handling localised and non localised blocks when creating & merging drafts.
- [#562](https://github.com/AcclaroInc/pm-craft-translations/issues/562)
**Added:**
- 
**Changed:**
- The block structure when merging in translated content for neo blocks.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: neo block issue

src/migrations/m241216_081944_upsert_program_id_column.php
Adding a migration to fix the program Id missing in the orders table. 
- 
**Added:**
- Added a new migration that runs and checks if program id exists, if not - adds it to the table. 
- 
**Fixed:**
- fixed the rollback method by adding a proper check to prevent rollback failures. 
-
**Checklist:**
=> #564: Migration fix for program id missing

src/services/repository/FileRepository.php
Entry in default site not found leading to error adding entry to existing order.
- #538 
**Added:**
- Source site specifically when fetching an order preventing error if source site does not exist in default site.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: error adding entry to existing order

src/assetbundles/src/js/RecentlyModified.js
Fixed widget overlapping issue in plugin dashboard.
- [#560](https://github.com/AcclaroInc/pm-craft-translations/issues/560)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> fixed: widget overlapping in plugin dashboard

docs/faq.md
Update docs/faq.md: Added new section on preventing static translations from being overwritten in production
- Added a new section under "Technical Issues" explaining how to prevent static translation files from being overwritten in production
=> Update docs/faq.md: static translations

src/services/repository/DraftRepository.php
Error notification will be shown if a draft fails to create or merge in delivered data, resulting in rollback of draft creation.
- [#576](https://github.com/AcclaroInc/pm-craft-translations/issues/576)
**Added:**
- Notification in draft merge/apply logic that will inform use why exactly the draft creation failed.
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
=> added: error notification on draft creation failure

src/services/repository/ActivityLogRepository.php
Though we are not able to find the concrete cause why did that happened in first place, However we have added craft's native date function for activity log date logging to prevent any such issue.
- #539 
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
**Checklist:**
**Logs after changes**
=> Activity log future date issue fix

src/assetbundles/src/css/Translations.css, src/assetbundles/src/js/RecentEntries.js, src/assetbundles/src/js/RecentlyModified.js, src/templates/_components/widgets/NewAndModifiedEntries/body.twig
Fixed feedback widget overlapping, some buttons extending outside parent divs & text alignment issues.
- [#560](https://github.com/AcclaroInc/pm-craft-translations/issues/560)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- 
Before fix:
After fix:
**Checklist:**
=> fixed: feedback widget overlapping

src/assetbundles/src/js/OrderDetails.js, src/services/repository/OrderRepository.php, src/templates/settings/clear-orders.twig, src/templates/settings/settings-check.twig
The user seeing a 404 page not found issue, I bealive it could be due to different cpTrigger than admin so changes the logic to fetch cpTrigger dynamically.
- [#619](https://github.com/AcclaroInc/pm-craft-translations/issues/619)
**Added:**
- 
**Changed:**
- The hard coded cpTrigger to dynamic.
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- Do not have steps to reproduce, so sid or merrit can QA this once its deployed to dev server.
**Checklist:**
___
Enhancement
___
- Use …
=> Fixed: cpTrigger issue in url

src/assetbundles/src/js/StaticTranslations.js, src/controllers/StaticTranslationsController.php
Make export button in static translations page downloads csv for all sites except default site. 
- [#610](https://github.com/AcclaroInc/pm-craft-translations/issues/610)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
-
**Security:**
-
- Tested locally.
- In order to test on dev just make sure the export button in static translations page when clicked downloads a zip file which includes static translations for all sites in csv format.
- And uploading the downloaded zip or single csv should reflect the uploaded content in target site.
**Checklist:** …
=> changed: export button defaults to all sites csv download

src/Translations.php, src/services/repository/DraftRepository.php, src/services/translator/Export_ImportTranslationService.php
Entry content is getting reverted to previous version when multiple draft are applied togather.
- [#609](https://github.com/AcclaroInc/pm-craft-translations/issues/609)
**Added:**
- 
**Changed:**
-
-
**Removed:**
-
**Fixed:**
- multiple draft content reversion issue.
**Security:**
-
Tested loacally.
Deployed on dev server for QA.
- Create an order with multiple target sites more than 3. (Use any entry with nested strucutures and also having localised fields at root level of entry)
- Translated the downloaded fiels and upload back.
- Create draft for more than 3 files togather.
- Apply all drafts togather and make sure every field in entry has the translated content.
- To be on safer side test all possible ways a user can create and apply drafts.
**Screenshots (if …
=> fixed: entry content reversion
